version: "3.9"
services:
  database:
    image: postgres:12
    container_name: database
    restart: always
    env_file: .env
    ports:
      - "7000:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    restart: always
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/go/src/github.com/francoggm/go_expenses_api/logs
volumes:
  data: